baseurl = "https://nazavode.github.io/"
languageCode = "en-us"
title = "/dev/null"

theme = "refuse"
enableEmoji = true

[permalinks]
    post = "/blog/:filename/"

[params]
  author = "Federico Ficarelli"
  description = "A bit more than nothing to see here."
  copyright = "&copy; 2020 Federico Ficarelli (<a href='https://keybase.io/nazavode'>@nazavode</a>). All rights reserved."
  
  [params.feedback]
        github = "nazavode/nazavode.github.io"

[markup]
    [markup.highlight]
        style = "pygments"

[menu]
    [[menu.main]]
        name = "blog"
        url = "/blog/"
        weight = 1
    [[menu.main]]
        name = "about"
        url = "/about/"
        weight = 100
