baseurl = "https://451.sh/"
languageCode = "en-us"
title = "~"

theme = "refuse"
enableEmoji = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
    post = "/post/:filename/"

[params]
  author = "Federico Ficarelli"
  description = "A time to break down, and a time to build up."

  [params.feedback]
        github = "nazavode/nazavode.github.io"

[markup]
    [markup.highlight]
        style = "pygments"
    # TODO workaround for link lists, remove when
    # a proper layout is available:
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[menu]
    [[menu.main]]
        name = "post"
        url = "/post/"
        weight = 1
    [[menu.main]]
        name = "misc"
        url = "/misc/"
        weight = 2
    [[menu.main]]
        name = "about"
        url = "/about/"
        weight = 3