baseurl = "https://451.sh/"
languageCode = "en-us"
title = "~"

theme = "refuse"
enableEmoji = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
    post = "/blog/:filename/"

[params]
  author = "Federico Ficarelli"
  description = "A time to break down, and a time to build up."

  [params.feedback]
        github = "nazavode/nazavode.github.io"

[markup]
    [markup.highlight]
        style = "pygments"

[menu]
    [[menu.main]]
        name = "blog"
        url = "/blog/"
        weight = 1
    [[menu.main]]
        name = "about"
        url = "/about/"
        weight = 100
